### ISSUE TITLE
cross reference issue

### ISSUE THREAD

**Issue by xiongjiamu** [xxmcyr/xsn_admin#2]
2222

**Comment by xiongjiamu** [comment]
#1

**Comment by miykaelxiong** [comment]
我可以更改吗

**Comment by xiongjiamu** [comment]
arco-design/arco-design 里面有个 issue，可以下载到 Figma 中需要的字体

arco-design/arco-design/issues/52

**Comment by xiongjiamu** [comment]
arco-design/arco-design Repo

**Comment by xiongjiamu** [comment]
arco-design/arco-design/
